apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBroker
metadata:
  name: astra
spec:
  authInfo:
    basic:
      secretRef:
        name: astra-creds
  url: https://broker.astra.datastax.com/
